### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by heycarsten** [heycarsten/ember-fsm#10]
Ensure Ember FSM can be used easily in Ember CLI projects.

**Comment by tobsch** [comment]
+1

**Comment by gogogarrett** [comment]
@heycarsten any update on the state of this?

**Comment by heycarsten** [comment]
@gogogarrett Update is if people still see value in Ember FSM and use it, I'll convert it into an addon.

**Comment by gogogarrett** [comment]
@heycarsten heycarsten,

I work at [Blake Education](http://dev.blake.com.au/) where we make apps to help children learn around the world.

We have used ember-fsm for a major part of one our apps to [create a realtime multiplayer game](http://readingeggspress.com.au/schools/stadium). We are currently porting all our apps across to ember-cli and would love to use ember-fsm if possible.

We use [pusher.js](https://pusher.com/) to handle the websockets. We rely heavily on the promise-awareness that your library provides.

I can give you some more specifics of the project if you're interested.

Thanks

**Comment by heycarsten** [comment]
@gogogarrett Say no more, I'll update the library to be an addon 💃

**Comment by gogogarrett** [comment]
@heycarsten any update on this? My team and I are willing and able to help out with this if you need a hand. Would you like to discuss the steps needed to make this happen?

**Comment by heycarsten** [comment]
Hi @gogogarrett I started doing this back in August and was unable to continue. I was basically moving the entire codebase over to an Ember addon. I will put this in a branch and publish it, I was thinking it might be okay to release it as 1.0, it will break everything. I'll make a branch right now and comment when it's published.

**Comment by heycarsten** [comment]
@gogogarrett I've put the initial work I did into the branch `addonify` https://github.com/heycarsten/ember-fsm/tree/addonify

**Comment by heycarsten** [comment]
🎉 DONE!!! 🎉

**Comment by hhff** [comment]
WOAH
