### ISSUE TITLE
$all does not include $initial

### ISSUE THREAD

**Issue by hhff** [heycarsten/ember-fsm#12]
There's probably a good reason for this, but I was hoping to do:

```js
fsmEvents: {
  toCart: {
    transition: { $all: 'cart' }
}
```

Instead I need to do:
```js
fsmEvents: {
  toCart: {
    transition: { 
      from: ['$initial', '$all'],
      to: 'cart'
    }
  }
}
```

Feels like $all should include $initial - but maybe I'm missing something?

**Comment by hhff** [comment]
Some context - I don't know the initial state of my state machine until an ajax call returns.

Ideally I'd like to be able to set `initialState` dynamically, and then trigger state machine initialization after a promise returns from the server, but that doesn't seem possible, so instead I'm starting the machine in state `initialized` and then when the promise returns transitioning it to the correct state.

**Comment by hhff** [comment]
Haha never mind, i was tripping

I forgot there needs to be a way to get back in the initial state - I wasn't declaring that...

**Comment by heycarsten** [comment]
Oh, no worries! I really feel like the public API could be better, I have to give this project some love and bring it back up to speed given all of the things that have changed in the past year.
