### ISSUE TITLE
It should work with prototype extensions disabled

### ISSUE THREAD

**Issue by hhff** [heycarsten/ember-fsm#14]
just updated an addon that uses this to CLI 0.0.23 (which includes a package for addons that forces ember to disable prototype extensions, to ensure max compatibility)

Noticed ember-fsm uses .contains

Just flagging this, shouldn't be too hard

**Comment by heycarsten** [comment]
Hey @hhff sorry for dragging my butt on this, I'm going to patch it for you right now.

**Comment by hhff** [comment]
Oh @heycarsten you're the man!  It's been getting pushed lower on my to do list for a few weeks now :+1:
