### ISSUE TITLE
Found another Prototype Extension!

### ISSUE THREAD

**Issue by hhff** [heycarsten/ember-fsm#16]
Hey Carsten!!

miss u man!  [found another lil prototype extension we should snip](https://github.com/heycarsten/ember-fsm/blob/7d14e0a3545ce77c97c0411e7f9906506c020a43/lib/machine.js#L102)

<3

**Comment by heycarsten** [comment]
:heart: 

Hmm, I guess as long as that array is passed through `Ember.A()` first, we're good to use those methods? I'll look into it.

**Comment by hhff** [comment]
I guess so!  (≖ლ≖๑ )ﾌ
