### ISSUE TITLE
currentState in Stateful mixin conflicts with Ember Component property name

### ISSUE THREAD

**Issue by AndyPyeSC** [heycarsten/ember-fsm#18]
Using the Stateful mixin in a component results in the error "Uncaught TypeError: this.currentState.legacyPropertyDidChange is not a function", as reported at emberjs/ember.js#11374

**Comment by heycarsten** [comment]
Thanks for letting me know!

**Comment by AndyPyeSC** [comment]
No problem! How about renaming it to fsmCurrentState, to be consistent with fsmStates, fsmEvents etc.?

**Comment by heycarsten** [comment]
@AndyPyeSC Yes, that makes the most sense to me. We did some work a while ago for sniffing out an existing `currentState` property and adding ours only if an existing one didn't exist, to fix this issue while maintaining backwards compatibility. You are the second person to report this issue so I think it's time to fix it. I'll make it happen as soon as I can.

**Comment by AndyPyeSC** [comment]
@heycarsten That's great, thanks! I've made my own changes in andypyesc/ember-fsm@2d25e719b4edd3240f34adade9f2c82c1c31381c but I'm guessing that's too simplistic for what you're looking to achieve - I just wanted to get something working for an experiment I'm working on.

**Comment by devinus** [comment]
This would really help. I unfortunately can't use `ember-fsm` with my component until this is resolved. :(

**Comment by tobsch** [comment]
+1

**Comment by heycarsten** [comment]
Hey @AndyPyeSC, I decided to just merge this in with @tobsch's changes, thanks for your contribution.

**Comment by AndyPyeSC** [comment]
Great, thanks!
