### ISSUE TITLE
Auto populate canXXX properties

### ISSUE THREAD

**Issue by ssured** [heycarsten/ember-fsm#5]
I love the automatic `isInXXX` properties, it's genius for logic in templates. It would be really nice to have `canXXX` properties too. XXX is replaced with the name of a transition.

This allows for templates to add action buttons when these actions are available.

What is your opinion, is this hard to implement?

I think recomputing the guards will be hard though.

**Comment by heycarsten** [comment]
I'm closing this for now because it's 3 years later and I still don't know how to do this in an efficient way 😩
